export function brewInstallCommand(tokens: string[]): string {
  if (tokens.length === 0) return "";
  return `brew install --cask ${tokens.join(" ")}`;
}

export function brewfile(tokens: string[]): string {
  if (tokens.length === 0) return "";
  const lines = tokens.map((t) => `cask "${t}"`);
  return [
    "# Brewfile generated by casky.app",
    "# Run with: brew bundle --file=./Brewfile",
    "",
    ...lines,
    "",
  ].join("\n");
}

export function curlOneLiner(tokens: string[]): string {
  if (tokens.length === 0) return "";
  const list = tokens.join(" ");
  return [
    `command -v brew >/dev/null || /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)" && \\`,
    `brew install --cask ${list}`,
  ].join("\n");
}

export function shareUrl(origin: string, encoded: string): string {
  if (!encoded) return origin;
  return `${origin.replace(/\/$/, "")}/share/${encoded}`;
}
