const QUALIFIED_TOKEN = /^([\w.-]+\/[\w.-]+)\/([\w.-]+)$/;

/**
 * A cart token is either a plain cask (`firefox`) or a fully-qualified token
 * from a custom tap (`charmbracelet/tap/mods`). For qualified tokens, split off
 * the `owner/repo` tap from the trailing cask name.
 */
export function splitTap(
  token: string,
): { tap: string; name: string } | null {
  const m = QUALIFIED_TOKEN.exec(token);
  return m ? { tap: m[1], name: m[2] } : null;
}

export function isQualifiedToken(token: string): boolean {
  return QUALIFIED_TOKEN.test(token);
}

export function brewInstallCommand(tokens: string[]): string {
  if (tokens.length === 0) return "";
  // `brew install --cask owner/repo/name` auto-taps, so qualified tokens
  // need no separate `brew tap` step here.
  return `brew install --cask ${tokens.join(" ")}`;
}

export function brewfile(tokens: string[]): string {
  if (tokens.length === 0) return "";
  const taps = new Set<string>();
  const casks: string[] = [];
  for (const t of tokens) {
    const q = splitTap(t);
    if (q) {
      taps.add(q.tap);
      casks.push(q.name);
    } else {
      casks.push(t);
    }
  }
  const tapLines = [...taps].map((t) => `tap "${t}"`);
  return [
    "# Brewfile generated by casky.app",
    "# Save to ~/Downloads/Brewfile, then run:",
    "#   cd ~/Downloads && brew bundle",
    "",
    ...(tapLines.length ? [...tapLines, ""] : []),
    ...casks.map((t) => `cask "${t}"`),
    "",
  ].join("\n");
}

export function curlOneLiner(tokens: string[]): string {
  if (tokens.length === 0) return "";
  const list = tokens.join(" ");
  const installBrew =
    `NONINTERACTIVE=1 /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"`;
  const sourceBrew =
    `eval "$(/opt/homebrew/bin/brew shellenv 2>/dev/null || /usr/local/bin/brew shellenv)"`;
  return `command -v brew >/dev/null || ( ${installBrew} && ${sourceBrew} ) && brew install --quiet --cask ${list}`;
}

export function shareUrl(origin: string, encoded: string): string {
  if (!encoded) return origin;
  return `${origin.replace(/\/$/, "")}/share/${encoded}`;
}

export type CronSchedule = "daily" | "weekly" | "monthly";

const CRON_EXPR: Record<CronSchedule, string> = {
  daily: "0 9 * * *",
  weekly: "0 9 * * 1",
  monthly: "0 9 1 * *",
};

export const CRON_LABEL: Record<CronSchedule, string> = {
  daily: "Daily, 9am",
  weekly: "Weekly, Mon 9am",
  monthly: "Monthly, 1st 9am",
};

export function cronOneLiner(schedule: CronSchedule): string {
  const expr = CRON_EXPR[schedule];
  const job = `${expr} /bin/bash -lc "brew update -q && brew upgrade --cask -q" # casky`;
  return `(crontab -l 2>/dev/null | grep -v '# casky'; echo '${job}') | crontab -`;
}

export const CRON_REMOVE = `crontab -l | grep -v '# casky' | crontab -`;
