export function brewInstallCommand(tokens: string[]): string {
  if (tokens.length === 0) return "";
  return `brew install --cask ${tokens.join(" ")}`;
}

export function brewfile(tokens: string[]): string {
  if (tokens.length === 0) return "";
  const lines = tokens.map((t) => `cask "${t}"`);
  return [
    "# Brewfile generated by casky.app",
    "# Save to ~/Downloads/Brewfile, then run:",
    "#   cd ~/Downloads && brew bundle",
    "",
    ...lines,
    "",
  ].join("\n");
}

export function curlOneLiner(tokens: string[]): string {
  if (tokens.length === 0) return "";
  const list = tokens.join(" ");
  const installBrew =
    `NONINTERACTIVE=1 /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"`;
  const sourceBrew =
    `eval "$(/opt/homebrew/bin/brew shellenv 2>/dev/null || /usr/local/bin/brew shellenv)"`;
  return `command -v brew >/dev/null || ( ${installBrew} && ${sourceBrew} ) && brew install --quiet --cask ${list}`;
}

export function shareUrl(origin: string, encoded: string): string {
  if (!encoded) return origin;
  return `${origin.replace(/\/$/, "")}/share/${encoded}`;
}
