import Foundation
import Testing
@testable import Casky

@Suite struct RefTests {
    @Test func parsesPlainAndQualifiedNames() throws {
        let plain = try Ref(parsing: "Firefox")
        #expect(plain.tap == nil)
        #expect(plain.fullName == "firefox")

        let qualified = try Ref(parsing: "charmbracelet/homebrew-tap/mods")
        #expect(qualified.tap == "charmbracelet/tap")
        #expect(qualified.fullName == "charmbracelet/tap/mods")
    }

    @Test func builtinTapsCollapseToPlainNames() throws {
        let viaBuiltinTap = try Ref(parsing: "homebrew/cask/firefox")
        #expect(viaBuiltinTap == (try Ref(parsing: "firefox")))
        #expect(try Ref(parsing: "homebrew/core/git").tap == nil)
    }

    @Test(arguments: ["", "a/b", "a/b/c/d", "a//c", "fire fox", "evil\"name", "a/homebrew-/c", "x;rm"])
    func rejectsMalformedNames(_ raw: String) {
        #expect(throws: RefError.invalid(raw)) { try Ref(parsing: raw) }
    }

    @Test func codableRoundTripValidatesOnDecode() throws {
        let items: [Item] = [.cask(try Ref(parsing: "a/b/c")), .formula(try Ref(parsing: "git")), .mas(id: 1, name: "X")]
        let data = try JSONEncoder().encode(items)
        #expect(try JSONDecoder().decode([Item].self, from: data) == items)

        let valid = Data(#"{"cask":"firefox"}"#.utf8)
        #expect(try JSONDecoder().decode(Item.self, from: valid) == .cask(try Ref(parsing: "firefox")))
        for tampered in [#"{"cask":"bad name"}"#, #"{"cask":"a","formula":"b"}"#, "{}"] {
            #expect(throws: (any Error).self) { try JSONDecoder().decode(Item.self, from: Data(tampered.utf8)) }
        }
    }

    @Test func sameNameDifferentKindAreDifferentItems() throws {
        let docker = try Ref(parsing: "docker")
        #expect(Set([Item.cask(docker), Item.formula(docker)]).count == 2)
    }
}

@Suite struct BrewfileTests {
    @Test func rendersAllKindsWithTapsAndMasTool() throws {
        let selection: [Item] = [
            .cask(try Ref(parsing: "docker")),
            .formula(try Ref(parsing: "docker")),
            .cask(try Ref(parsing: "charmbracelet/tap/mods")),
            .formula(try Ref(parsing: "hashicorp/tap/terraform")),
            .mas(id: 497799835, name: "Xcode"),
            .cask(try Ref(parsing: "docker")),
        ]
        #expect(Brewfile.render(selection) == """
            # Generated by casky. Install with: brew bundle --file=<this file>

            tap "charmbracelet/tap"
            tap "hashicorp/tap"

            brew "docker"
            brew "hashicorp/tap/terraform"
            brew "mas"

            cask "docker"
            cask "charmbracelet/tap/mods"

            mas "Xcode", id: 497799835

            """)
    }

    @Test func escapesRubyStringLiterals() {
        let text = Brewfile.render([.mas(id: 1, name: #"A "B" #{x} \ C"#)])
        #expect(text.contains(##"mas "A \"B\" \#{x} \\ C", id: 1"##))
    }

    @Test func doesNotDuplicateExplicitMasFormula() throws {
        let text = Brewfile.render([.formula(.masTool), .mas(id: 1, name: "X")])
        #expect(text.components(separatedBy: #"brew "mas""#).count == 2)
    }
}

@Suite struct InstallPlanTests {
    private func ref(_ raw: String) throws -> Ref { try Ref(parsing: raw) }

    @Test func ordersTapsFormulaeCasksAppsWithAdminLast() throws {
        let zoom = Item.cask(try ref("zoom"))
        let tool = Item.cask(try ref("a/b/tool"))
        let selection: [Item] = [
            .mas(id: 7, name: "App"),
            zoom,
            .cask(try ref("firefox")),
            .formula(try ref("git")),
            tool,
        ]
        let plan = InstallPlan(selection: selection, installed: InstalledState(), needsAdmin: [zoom])

        #expect(plan.steps.map(\.action) == [
            .tap("a/b"),
            .install(.formula(.masTool)),
            .install(.formula(try ref("git"))),
            .install(.cask(try ref("firefox"))),
            .install(tool),
            .install(zoom),
            .install(.mas(id: 7, name: "App")),
        ])
        #expect(plan.steps.first { $0.action == .install(tool) }?.prerequisites == [.tap("a/b")])
        #expect(plan.steps.last?.prerequisites == [.install(.formula(.masTool))])
    }

    @Test func skipsInstalledItemsAndExistingTaps() throws {
        var installed = InstalledState()
        installed.casks = ["firefox"]
        installed.formulae = ["mas"]
        installed.taps = ["a/b"]
        let selection: [Item] = [.cask(try ref("firefox")), .cask(try ref("a/b/tool")), .mas(id: 7, name: "App")]

        let plan = InstallPlan(selection: selection, installed: installed)

        #expect(plan.alreadyInstalled == [.cask(try ref("firefox"))])
        #expect(plan.steps.map(\.action) == [.install(.cask(try ref("a/b/tool"))), .install(.mas(id: 7, name: "App"))])
        #expect(plan.steps.allSatisfy { $0.prerequisites.isEmpty })
    }

    @Test func dedupesTapsAndSelection() throws {
        let tool = Item.cask(try ref("a/b/one"))
        let plan = InstallPlan(selection: [tool, .formula(try ref("a/homebrew-b/two")), tool], installed: InstalledState())
        #expect(plan.steps.map(\.action) == [
            .tap("a/b"),
            .install(.formula(try ref("a/b/two"))),
            .install(tool),
        ])
    }

    @Test func emptyWhenEverythingIsInstalled() throws {
        var installed = InstalledState()
        installed.formulae = ["git"]
        let plan = InstallPlan(selection: [.formula(try ref("git"))], installed: installed)
        #expect(plan.steps.isEmpty)
        #expect(plan.alreadyInstalled.count == 1)
    }
}

@Suite struct KitTests {
    @Test func bundledKitsDecode() throws {
        let url = try #require(Bundle.main.url(forResource: "kits", withExtension: "json"))
        let kits = try JSONDecoder().decode([Kit].self, from: Data(contentsOf: url))
        #expect(kits.count == 16)
        #expect(Set(kits.map(\.slug)).count == kits.count)
        #expect(kits.allSatisfy { !$0.items.isEmpty && $0.items.count == $0.items.uniqued().count })
    }
}

@Suite struct CatalogTests {
    private let casks = Data(#"""
    [
      {"token": "zoom", "name": ["Zoom"], "desc": "Video calls", "homepage": "https://zoom.us", "deprecated": false, "disabled": false,
       "artifacts": [{"uninstall": [{"pkgutil": "us.zoom"}]}, {"pkg": ["zoom.pkg"]}]},
      {"token": "firefox", "name": ["Mozilla Firefox"], "desc": "Web browser", "homepage": "https://firefox.com", "deprecated": false, "disabled": false,
       "artifacts": [{"app": ["Firefox.app"]}, ["odd", "shape"]]},
      {"token": "old", "name": ["Old"], "desc": null, "homepage": null, "deprecated": true, "disabled": false, "artifacts": []},
      {"token": "Bad Token", "name": ["Bad"], "desc": null, "homepage": null, "deprecated": false, "disabled": false, "artifacts": []}
    ]
    """#.utf8)
    private let formulae = Data(#"""
    [
      {"name": "git", "desc": "Distributed revision control", "homepage": "https://git-scm.com", "deprecated": false, "disabled": false},
      {"name": "firefoxpwa", "desc": "Progressive web apps for Firefox", "homepage": null, "deprecated": false, "disabled": false},
      {"name": "gone", "desc": null, "homepage": null, "deprecated": false, "disabled": true}
    ]
    """#.utf8)
    private let caskInstalls = Data(#"{"items": [{"cask": "firefox", "count": "1,234"}, {"cask": "zoom", "count": "99"}]}"#.utf8)
    private let formulaInstalls = Data(#"{"items": [{"formula": "git", "count": "5,000"}, {"formula": "firefoxpwa", "count": 10}]}"#.utf8)

    private func catalog() throws -> Catalog {
        Catalog(entries: try Catalog.decodeHomebrew(casks: casks, formulae: formulae, caskInstalls: caskInstalls, formulaInstalls: formulaInstalls))
    }

    @Test func decodesActiveEntriesWithAnalyticsAndAdminFlag() throws {
        let catalog = try catalog()
        #expect(catalog.entries.map(\.title) == ["git", "firefoxpwa", "Zoom", "Mozilla Firefox"])
        let zoom = try #require(catalog.entry(for: .cask(try Ref(parsing: "zoom"))))
        #expect(zoom.needsAdmin && zoom.installs == 99)
        #expect(catalog.adminItems == [zoom.item])
        #expect(catalog.entry(for: .formula(try Ref(parsing: "firefoxpwa")))?.installs == 10)
    }

    @Test func worksWithoutAnalytics() throws {
        let entries = try Catalog.decodeHomebrew(casks: casks, formulae: formulae, caskInstalls: nil, formulaInstalls: Data("garbage".utf8))
        #expect(entries.count == 4 && entries.allSatisfy { $0.installs == 0 })
    }

    @Test func ranksByMatchQualityThenPopularity() throws {
        let catalog = try catalog()
        #expect(catalog.search("firefox").map(\.title) == ["Mozilla Firefox", "firefoxpwa"])
        #expect(catalog.search("FIRE", kind: .formula).map(\.title) == ["firefoxpwa"])
        #expect(catalog.search("video").map(\.title) == ["Zoom"])
        #expect(catalog.search("").map(\.title) == ["git", "Mozilla Firefox", "Zoom", "firefoxpwa"])
        #expect(catalog.search("nothing-matches").isEmpty)
    }

    @Test func appStoreKeepsMacAppsOnly() throws {
        let data = Data(#"""
        {"resultCount": 2, "results": [
          {"trackId": 497799835, "trackName": "Xcode", "kind": "mac-software", "description": "Build apps.\nMore text", "trackViewUrl": "https://apps.apple.com/app/id497799835"},
          {"trackId": 640199958, "trackName": "Apple Developer", "kind": "software", "description": "iPad app"}
        ]}
        """#.utf8)
        let entries = try AppStoreSearch.decode(data)
        #expect(entries.map(\.item) == [.mas(id: 497799835, name: "Xcode")])
        #expect(entries.first?.summary == "Build apps.")
        #expect(AppStoreSearch.url(for: "ia writer").absoluteString.contains("term=ia%20writer"))
    }
}

@Suite struct InstalledStateTests {
    @Test func decodesHomebrewTapsAndMas() throws {
        let brewInfo = Data(#"""
        {"formulae": [{"name": "git", "full_name": "git", "installed": [{"installed_on_request": true}]},
                      {"name": "pcre2", "full_name": "pcre2", "installed": [{"installed_on_request": false}]},
                      {"name": "terraform", "full_name": "hashicorp/tap/terraform", "installed": [{}]}],
         "casks": [{"token": "mods", "full_token": "charmbracelet/tap/mods"}, {"token": "firefox", "full_token": "firefox"}]}
        """#.utf8)
        let tapInfo = Data(#"[{"name": "hashicorp/tap"}, {"name": "charmbracelet/tap"}]"#.utf8)
        let masList = Data(#"""
        {"adamID":497799835,"bundleID":"com.apple.dt.Xcode","name":"Xcode","version":"16.0"}
        {
          "adamID": "937984704",
          "name": "Amph {etamine} \"x\"",
          "nested": {"a": [1, {"b": "}"}]}
        }
        """#.utf8)
        let state = try InstalledState.decode(brewInfo: brewInfo, tapInfo: tapInfo, masList: masList)

        #expect(state.contains(.formula(try Ref(parsing: "hashicorp/homebrew-tap/terraform"))))
        #expect(state.contains(.cask(try Ref(parsing: "charmbracelet/tap/mods"))))
        #expect(!state.contains(.formula(try Ref(parsing: "firefox"))))
        #expect(state.masApps == [497799835: "Xcode", 937984704: #"Amph {etamine} "x""#])
        #expect(state.taps == ["hashicorp/tap", "charmbracelet/tap"])
        #expect(state.requestedFormulae == ["git"])
        #expect(state.snapshot() == [
            .formula(try Ref(parsing: "git")),
            .cask(try Ref(parsing: "charmbracelet/tap/mods")),
            .cask(try Ref(parsing: "firefox")),
            .mas(id: 937984704, name: #"Amph {etamine} "x""#),
            .mas(id: 497799835, name: "Xcode"),
        ])
    }

    @Test func emptyMasListAndMissingMas() throws {
        #expect(try InstalledState.parseMasList(Data()).isEmpty)
        #expect(throws: JSONStream.Malformed.self) { try InstalledState.parseMasList(Data(#"{"name": "x""#.utf8)) }
        #expect(throws: (any Error).self) { try InstalledState.decode(brewInfo: Data("{}".utf8), tapInfo: Data("[]".utf8), masList: nil) }
    }
}

@Suite struct BrewfileReadTests {
    @Test func roundTripsWhatTheWriterProduces() throws {
        let items: [Item] = [
            .formula(try Ref(parsing: "git")),
            .formula(try Ref(parsing: "hashicorp/tap/terraform")),
            .formula(.masTool),
            .cask(try Ref(parsing: "charmbracelet/tap/mods")),
            .mas(id: 1, name: #"A "B" #{x} \ C"#),
        ]
        let result = Brewfile.read(Brewfile.render(items))
        #expect(result == Brewfile.Import(items: items))
    }

    @Test func readsCommonHandWrittenForms() throws {
        let text = """
        # My setup
        tap "homebrew/bundle"
          brew 'git'   # version control
        brew "postgresql@16", restart_service: true
        cask "firefox", args: { appdir: "~/Apps" }
        mas "Xcode",id:497799835
        """
        let result = Brewfile.read(text)
        #expect(result.items == [
            .formula(try Ref(parsing: "git")),
            .formula(try Ref(parsing: "postgresql@16")),
            .cask(try Ref(parsing: "firefox")),
            .mas(id: 497799835, name: "Xcode"),
        ])
        #expect(result.skipped.isEmpty)
        #expect(result.optionsIgnored == 2)
    }

    @Test func skipsAnythingBeyondPlainLiterals() {
        let hostile = [
            ##"brew "#{`whoami`}""##,
            #"brew "x" if system("touch /tmp/pwned")"#,
            #"cask "a"; system "rm -rf ~""#,
            #"vscode "golang.go""#,
            #"tap "a/b", "https://example.com/b.git""#,
            #"mas "X", id: 1, extra: true"#,
            #"mas "X""#,
            #"brew "bad name""#,
            #"brew "unterminated"#,
            #"brew "tab\there""#,
            "if OS.mac?",
            "brew(\"x\")",
        ]
        let result = Brewfile.read(hostile.joined(separator: "\n"))
        #expect(result.items.isEmpty)
        #expect(result.skipped == hostile)
    }
}

@Suite struct RunStateTests {
    private func ref(_ raw: String) throws -> Ref { try Ref(parsing: raw) }

    @Test func runsStepsInOrderAndSkipsDependentsOfFailures() throws {
        let tool = Item.cask(try ref("a/b/tool"))
        let git = Item.formula(try ref("git"))
        let app = Item.mas(id: 7, name: "App")
        var run = RunState(plan: InstallPlan(selection: [tool, git, app], installed: InstalledState()))

        #expect(run.nextStep()?.action == .tap("a/b"))
        run.finish(.failed(status: 1, output: ["no such tap"]))
        #expect(run.nextStep()?.action == .install(.formula(.masTool)))
        run.finish(.installed)
        #expect(run.nextStep()?.action == .install(git))
        run.finish(.installed)
        // tool's tap failed, so it is skipped without running.
        #expect(run.nextStep()?.action == .install(app))
        run.finish(.installed)
        #expect(run.nextStep() == nil)

        #expect(run.isFinished)
        #expect(run.outcomes[.install(tool)] == .skipped(reason: "a/b didn't install"))
        #expect(run.failedCount == 1)
    }

    @Test func stopFinishesCurrentStepThenSkipsTheRest() throws {
        let items = try ["a", "b", "c"].map { Item.cask(try ref($0)) }
        var run = RunState(plan: InstallPlan(selection: items, installed: InstalledState()))

        #expect(run.nextStep()?.action == .install(items[0]))
        run.requestStop()
        run.finish(.installed)
        #expect(run.nextStep() == nil)
        #expect(run.outcomes[.install(items[0])] == .installed)
        #expect(run.outcomes[.install(items[1])] == .skipped(reason: "Stopped"))
        #expect(run.outcomes[.install(items[2])] == .skipped(reason: "Stopped"))
        #expect(run.isFinished)
    }

    @Test func emptyPlanIsFinishedImmediately() {
        var run = RunState(plan: InstallPlan(selection: [], installed: InstalledState()))
        #expect(run.nextStep() == nil && run.isFinished)
    }
}

@Suite struct WebIconsTests {
    @Test func ranksDeclaredIconsBySizeAndPutsThemedOnesLast() {
        let html = Data("""
        <!doctype html><html><head>
        <link rel="icon" href="/favicon-32.png" sizes="32x32">
        <link rel="icon" href="/light.svg" media="(prefers-color-scheme: light)">
        <link rel="apple-touch-icon" href="/touch.png">
        <link rel="icon" href="https://cdn.example.com/icon-196.png" sizes="196x196" type="image/png">
        <link rel="stylesheet" href="/style.css">
        <link rel="icon" href="http://insecure.example.com/x.png" sizes="512x512">
        </head><body><p>Hi</body></html>
        """.utf8)
        let icons = WebIcons.declared(in: html, baseURL: URL(string: "https://example.com/product/")!)
        #expect(icons.map(\.absoluteString) == [
            "https://cdn.example.com/icon-196.png",
            "https://example.com/touch.png",
            "https://example.com/favicon-32.png",
            "https://example.com/light.svg",
        ])
    }

    @Test func toleratesPagesWithoutIcons() {
        #expect(WebIcons.declared(in: Data("not html at all".utf8), baseURL: URL(string: "https://example.com")!).isEmpty)
    }
}
