import Foundation
import Testing
@testable import Casky

@Suite struct RefTests {
    @Test func parsesPlainAndQualifiedNames() throws {
        let plain = try Ref(parsing: "Firefox")
        #expect(plain.tap == nil)
        #expect(plain.fullName == "firefox")

        let qualified = try Ref(parsing: "charmbracelet/homebrew-tap/mods")
        #expect(qualified.tap == "charmbracelet/tap")
        #expect(qualified.fullName == "charmbracelet/tap/mods")
    }

    @Test func builtinTapsCollapseToPlainNames() throws {
        let viaBuiltinTap = try Ref(parsing: "homebrew/cask/firefox")
        #expect(viaBuiltinTap == (try Ref(parsing: "firefox")))
        #expect(try Ref(parsing: "homebrew/core/git").tap == nil)
    }

    @Test(arguments: ["", "a/b", "a/b/c/d", "a//c", "fire fox", "evil\"name", "a/homebrew-/c", "x;rm"])
    func rejectsMalformedNames(_ raw: String) {
        #expect(throws: RefError.invalid(raw)) { try Ref(parsing: raw) }
    }

    @Test func codableRoundTripValidatesOnDecode() throws {
        let items: [Item] = [.cask(try Ref(parsing: "a/b/c")), .formula(try Ref(parsing: "git")), .mas(id: 1, name: "X")]
        let data = try JSONEncoder().encode(items)
        #expect(try JSONDecoder().decode([Item].self, from: data) == items)

        let valid = Data(#"{"cask":{"_0":"firefox"}}"#.utf8)
        #expect(try JSONDecoder().decode(Item.self, from: valid) == .cask(try Ref(parsing: "firefox")))
        let tampered = Data(#"{"cask":{"_0":"bad name"}}"#.utf8)
        #expect(throws: (any Error).self) { try JSONDecoder().decode(Item.self, from: tampered) }
    }

    @Test func sameNameDifferentKindAreDifferentItems() throws {
        let docker = try Ref(parsing: "docker")
        #expect(Set([Item.cask(docker), Item.formula(docker)]).count == 2)
    }
}

@Suite struct BrewfileTests {
    @Test func rendersAllKindsWithTapsAndMasTool() throws {
        let selection: [Item] = [
            .cask(try Ref(parsing: "docker")),
            .formula(try Ref(parsing: "docker")),
            .cask(try Ref(parsing: "charmbracelet/tap/mods")),
            .formula(try Ref(parsing: "hashicorp/tap/terraform")),
            .mas(id: 497799835, name: "Xcode"),
            .cask(try Ref(parsing: "docker")),
        ]
        #expect(Brewfile.render(selection) == """
            # Generated by casky. Install with: brew bundle --file=<this file>

            tap "charmbracelet/tap"
            tap "hashicorp/tap"

            brew "docker"
            brew "hashicorp/tap/terraform"
            brew "mas"

            cask "docker"
            cask "charmbracelet/tap/mods"

            mas "Xcode", id: 497799835

            """)
    }

    @Test func escapesRubyStringLiterals() {
        let text = Brewfile.render([.mas(id: 1, name: #"A "B" #{x} \ C"#)])
        #expect(text.contains(##"mas "A \"B\" \#{x} \\ C", id: 1"##))
    }

    @Test func doesNotDuplicateExplicitMasFormula() throws {
        let text = Brewfile.render([.formula(.masTool), .mas(id: 1, name: "X")])
        #expect(text.components(separatedBy: #"brew "mas""#).count == 2)
    }
}

@Suite struct InstallPlanTests {
    private func ref(_ raw: String) throws -> Ref { try Ref(parsing: raw) }

    @Test func ordersTapsFormulaeCasksAppsWithAdminLast() throws {
        let zoom = Item.cask(try ref("zoom"))
        let tool = Item.cask(try ref("a/b/tool"))
        let selection: [Item] = [
            .mas(id: 7, name: "App"),
            zoom,
            .cask(try ref("firefox")),
            .formula(try ref("git")),
            tool,
        ]
        let plan = InstallPlan(selection: selection, installed: InstalledState(), needsAdmin: [zoom])

        #expect(plan.steps.map(\.action) == [
            .tap("a/b"),
            .install(.formula(.masTool)),
            .install(.formula(try ref("git"))),
            .install(.cask(try ref("firefox"))),
            .install(tool),
            .install(zoom),
            .install(.mas(id: 7, name: "App")),
        ])
        #expect(plan.steps.first { $0.action == .install(tool) }?.prerequisites == [.tap("a/b")])
        #expect(plan.steps.last?.prerequisites == [.install(.formula(.masTool))])
    }

    @Test func skipsInstalledItemsAndExistingTaps() throws {
        var installed = InstalledState()
        installed.casks = ["firefox"]
        installed.formulae = ["mas"]
        installed.taps = ["a/b"]
        let selection: [Item] = [.cask(try ref("firefox")), .cask(try ref("a/b/tool")), .mas(id: 7, name: "App")]

        let plan = InstallPlan(selection: selection, installed: installed)

        #expect(plan.alreadyInstalled == [.cask(try ref("firefox"))])
        #expect(plan.steps.map(\.action) == [.install(.cask(try ref("a/b/tool"))), .install(.mas(id: 7, name: "App"))])
        #expect(plan.steps.allSatisfy { $0.prerequisites.isEmpty })
    }

    @Test func dedupesTapsAndSelection() throws {
        let tool = Item.cask(try ref("a/b/one"))
        let plan = InstallPlan(selection: [tool, .formula(try ref("a/homebrew-b/two")), tool], installed: InstalledState())
        #expect(plan.steps.map(\.action) == [
            .tap("a/b"),
            .install(.formula(try ref("a/b/two"))),
            .install(tool),
        ])
    }

    @Test func emptyWhenEverythingIsInstalled() throws {
        var installed = InstalledState()
        installed.formulae = ["git"]
        let plan = InstallPlan(selection: [.formula(try ref("git"))], installed: installed)
        #expect(plan.steps.isEmpty)
        #expect(plan.alreadyInstalled.count == 1)
    }
}
