import Foundation

/// Writes a saved setup as an Ansible playbook that sets up a Mac on its own:
/// `ansible-galaxy collection install community.general`, then
/// `ansible-playbook <file>`.
///
/// Every value that came from the user is emitted as a YAML `!unsafe` string
/// so Ansible never evaluates `{{ … }}` inside it as a template.
enum AnsiblePlaybook {
    /// Where the playbook clones the dotfiles repository.
    static let dotfilesCheckout = "~/.local/share/casky/dotfiles"

    static func render(_ setup: SavedSetup) -> String {
        var tasks: [String] = []
        var handlers: Set<String> = []
        let items = setup.items.uniqued()

        let taps = items.compactMap(\.tap).uniqued()
        var formulae = items.compactMap { if case .formula(let ref) = $0 { ref.fullName } else { nil } }
        let casks = items.compactMap { if case .cask(let ref) = $0 { ref.fullName } else { nil } }
        let apps = items.compactMap { if case .mas(let id, let name) = $0 { (id: id, name: name) } else { nil } }
        if !apps.isEmpty, !formulae.contains(Ref.masTool.fullName) { formulae.append(Ref.masTool.fullName) }

        if !taps.isEmpty {
            tasks.append(task("Add Homebrew taps", "community.general.homebrew_tap", ["name": list(taps)]))
        }
        if !formulae.isEmpty {
            tasks.append(task("Install command-line tools", "community.general.homebrew", ["name": list(formulae), "state": "present"]))
        }
        if !casks.isEmpty {
            tasks.append(task("Install apps", "community.general.homebrew_cask", ["name": list(casks), "state": "present"]))
        }
        if !apps.isEmpty {
            let names = apps.map { "# \($0.id): \(comment($0.name))" }.joined(separator: "\n")
            tasks.append(names + "\n" + task("Install App Store apps (sign in to the App Store first)", "community.general.mas", ["id": "[\(apps.map { String($0.id) }.joined(separator: ", "))]", "state": "present"]))
        }

        if let dotfiles = setup.dotfiles, !dotfiles.files.isEmpty {
            tasks += dotfilesTasks(dotfiles, setup: setup)
        }

        if let preferences = setup.macPreferences, !preferences.isEmpty {
            for preference in preferences {
                var arguments = ["domain": unsafe(preference.domain), "key": unsafe(preference.key)]
                if let value = preference.value {
                    arguments["type"] = switch value {
                    case .boolean: "bool"
                    case .integer: "int"
                    case .decimal: "float"
                    case .string: "string"
                    }
                    arguments["value"] = switch value {
                    case .boolean(let on): on ? "true" : "false"
                    case .integer(let number): String(number)
                    case .decimal(let number): String(number)
                    case .string(let text): unsafe(text)
                    }
                    arguments["state"] = "present"
                } else {
                    arguments["state"] = "absent"
                }
                let restart = restartHandler(for: preference)
                if let restart { handlers.insert(restart) }
                tasks.append(task("\(preference.value == nil ? "Reset" : "Set") \(comment(preference.title))", "community.general.osx_defaults", arguments, notify: restart))
            }
        }

        var playbook = """
        # Generated by casky from the setup "\(comment(setup.name))".
        # Run it on the Mac to set up:
        #   ansible-galaxy collection install community.general
        #   ansible-playbook \(fileName(for: setup))
        # Apps that use an installer package need your password; if one fails,
        # install it with `brew install --cask <name>` in Terminal.
        - name: \(quoted("Set up " + comment(setup.name)))
          hosts: localhost
          connection: local
          gather_facts: false
          environment:
            PATH: "/opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
          tasks:

        """
        playbook += tasks.isEmpty ? "    []\n" : tasks.map { indent($0, by: 4) }.joined(separator: "\n\n") + "\n"
        if !handlers.isEmpty {
            playbook += "\n  handlers:\n" + handlers.sorted().map { app in
                indent(task("Restart \(app)", "ansible.builtin.command", ["argv": list(["killall", app])], changedWhen: "true"), by: 4)
            }.joined(separator: "\n\n") + "\n"
        }
        return playbook
    }

    static func fileName(for setup: SavedSetup) -> String {
        let name = setup.name.lowercased().map { $0.isLetter || $0.isNumber ? $0 : "-" }
        let slug = String(name).split(separator: "-").joined(separator: "-")
        return (slug.isEmpty ? "setup" : slug) + ".yml"
    }

    // MARK: Dotfiles

    private static func dotfilesTasks(_ dotfiles: DotfilesConfiguration, setup: SavedSetup) -> [String] {
        let checkout = "\(dotfilesCheckout)/\(setup.id.uuidString.lowercased())"
        var git = ["repo": unsafe(dotfiles.repository), "dest": unsafe(checkout), "update": "true"]
        if !dotfiles.ref.isEmpty { git["version"] = unsafe(dotfiles.ref) }
        var tasks = [task("Download dotfiles", "ansible.builtin.git", git)]

        let parents = dotfiles.files.compactMap { file -> String? in
            let parent = (file.destination.value as NSString).deletingLastPathComponent
            return parent.isEmpty ? nil : parent
        }.uniqued()
        for parent in parents {
            tasks.append(task("Create ~/\(comment(parent))", "ansible.builtin.file", ["path": unsafe("~/" + parent), "state": "directory"]))
        }
        for file in dotfiles.files {
            let source = "\(checkout)/\(file.source.value)"
            let destination = "~/" + file.destination.value
            switch file.mode {
            case .link:
                tasks.append(task("Link ~/\(comment(file.destination.value))", "ansible.builtin.file",
                                  ["src": unsafe(source), "path": unsafe(destination), "state": "link", "force": "true"]))
            case .copy:
                // ditto copies a file onto a file and a folder's contents into
                // a folder, matching casky's own copy; `copy` would nest
                // folders. Commands get no shell, so paths are relative to ~.
                tasks.append(task("Copy ~/\(comment(file.destination.value))", "ansible.builtin.command",
                                  ["argv": list(["ditto", String(source.dropFirst(2)), file.destination.value]), "chdir": unsafe("~")], changedWhen: "true"))
            }
        }
        return tasks
    }

    // MARK: Preferences

    private static func restartHandler(for preference: MacPreference) -> String? {
        switch preference.domain {
        case "com.apple.dock": "Dock"
        case "com.apple.finder": "Finder"
        case "NSGlobalDomain" where preference.key == "AppleShowAllExtensions": "Finder"
        default: nil
        }
    }

    // MARK: YAML

    /// One task; arguments are already YAML scalars or flow sequences.
    static func task(_ name: String, _ module: String, _ arguments: [String: String], notify: String? = nil, changedWhen: String? = nil) -> String {
        var lines = ["- name: \(quoted(name))", "  \(module):"]
        lines += arguments.keys.sorted().map { "    \($0): \(arguments[$0]!)" }
        if let changedWhen { lines.append("  changed_when: \(changedWhen)") }
        if let notify { lines.append("  notify: \(quoted("Restart \(notify)"))") }
        return lines.joined(separator: "\n")
    }

    /// A flow sequence of user values, each `!unsafe`.
    static func list(_ values: [String]) -> String {
        "[" + values.map(unsafe).joined(separator: ", ") + "]"
    }

    /// A user value Ansible must not template.
    static func unsafe(_ value: String) -> String { "!unsafe " + quoted(value) }

    /// A YAML double-quoted scalar. JSON string escaping is valid YAML.
    static func quoted(_ value: String) -> String {
        let data = try! JSONEncoder.withoutEscapingSlashes.encode(value)
        return String(decoding: data, as: UTF8.self)
    }

    /// Free text inside a `#` comment or a task name: one line, and no
    /// braces or percent signs, since Ansible templates task names.
    private static func comment(_ value: String) -> String {
        String(value.map { "{}%".contains($0) || $0.isNewline ? " " : $0 })
            .split(separator: " ").joined(separator: " ")
    }

    private static func indent(_ text: String, by spaces: Int) -> String {
        let padding = String(repeating: " ", count: spaces)
        return text.split(separator: "\n", omittingEmptySubsequences: false).map { padding + $0 }.joined(separator: "\n")
    }
}

private extension JSONEncoder {
    static let withoutEscapingSlashes: JSONEncoder = {
        let encoder = JSONEncoder()
        encoder.outputFormatting = .withoutEscapingSlashes
        return encoder
    }()
}
