import Foundation

/// Renders a selection as a Brewfile that works on its own with `brew bundle`.
///
/// Import goes the other way through Homebrew's own parser (`brew bundle list`),
/// so this is a writer only.
enum Brewfile {
    static func render(_ items: [Item]) -> String {
        let items = items.uniqued()
        var taps: [String] = []
        var formulae: [Ref] = []
        var casks: [Ref] = []
        var apps: [(id: Int, name: String)] = []

        for item in items {
            if let tap = item.tap, !taps.contains(tap) { taps.append(tap) }
            switch item {
            case .formula(let ref): formulae.append(ref)
            case .cask(let ref): casks.append(ref)
            case .mas(let id, let name): apps.append((id, name))
            }
        }
        if !apps.isEmpty, !formulae.contains(.masTool) {
            formulae.append(.masTool)
        }

        let sections: [[String]] = [
            ["# Generated by casky. Install with: brew bundle --file=<this file>"],
            taps.map { "tap \(quoted($0))" },
            formulae.map { "brew \(quoted($0.fullName))" },
            casks.map { "cask \(quoted($0.fullName))" },
            apps.map { "mas \(quoted($0.name)), id: \($0.id)" },
        ]
        return sections.filter { !$0.isEmpty }
            .map { $0.joined(separator: "\n") }
            .joined(separator: "\n\n") + "\n"
    }

    /// A Ruby double-quoted literal. App Store names are free text, so escape
    /// backslashes, quotes and `#` (which would otherwise start interpolation).
    private static func quoted(_ value: String) -> String {
        var escaped = ""
        for character in value {
            switch character {
            case "\\", "\"", "#": escaped.append("\\")
            default: break
            }
            escaped.append(character)
        }
        return "\"\(escaped)\""
    }
}

extension Array where Element: Hashable {
    /// Elements in first-seen order with duplicates removed.
    func uniqued() -> [Element] {
        var seen = Set<Element>()
        return filter { seen.insert($0).inserted }
    }
}
